name: value_listenable_extensions
description: "Useful tools for working with `ValueListenable`s."
version: 1.1.1
homepage: https://github.com/LunaONE/value_listenable_extensions

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  code_builder: ^4.10.0

  dart_style: ^2.3.4
