// Generated by `./generate_combine_latest.sh`
//
// DO NOT EDIT MANUALLY
//

import 'package:flutter/foundation.dart';
import 'package:meta/meta.dart';
import 'package:value_listenable_extensions/value_listenable_extensions.dart';
import './value_listenable_view.dart';

@useResult
DisposableValueListenable<U> combineLatest2<T1, T2, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  U Function(
    T1 v1,
    T2 v2,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest3<T1, T2, T3, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest4<T1, T2, T3, T4, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest5<T1, T2, T3, T4, T5, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest6<T1, T2, T3, T4, T5, T6, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest7<T1, T2, T3, T4, T5, T6, T7, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest8<T1, T2, T3, T4, T5, T6, T7, T8, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U>
    combineLatest9<T1, T2, T3, T4, T5, T6, T7, T8, T9, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U>
    combineLatest10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  ValueListenable<T10> vl10,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
    T10 v10,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
    vl10.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
      vl10.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);
  vl10.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
      vl10.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U>
    combineLatest11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  ValueListenable<T10> vl10,
  ValueListenable<T11> vl11,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
    T10 v10,
    T11 v11,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
    vl10.value,
    vl11.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
      vl10.value,
      vl11.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);
  vl10.addListener(onChange);
  vl11.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
      vl10.removeListener(onChange);
      vl11.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U>
    combineLatest12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  ValueListenable<T10> vl10,
  ValueListenable<T11> vl11,
  ValueListenable<T12> vl12,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
    T10 v10,
    T11 v11,
    T12 v12,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
    vl10.value,
    vl11.value,
    vl12.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
      vl10.value,
      vl11.value,
      vl12.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);
  vl10.addListener(onChange);
  vl11.addListener(onChange);
  vl12.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
      vl10.removeListener(onChange);
      vl11.removeListener(onChange);
      vl12.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U>
    combineLatest13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  ValueListenable<T10> vl10,
  ValueListenable<T11> vl11,
  ValueListenable<T12> vl12,
  ValueListenable<T13> vl13,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
    T10 v10,
    T11 v11,
    T12 v12,
    T13 v13,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
    vl10.value,
    vl11.value,
    vl12.value,
    vl13.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
      vl10.value,
      vl11.value,
      vl12.value,
      vl13.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);
  vl10.addListener(onChange);
  vl11.addListener(onChange);
  vl12.addListener(onChange);
  vl13.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
      vl10.removeListener(onChange);
      vl11.removeListener(onChange);
      vl12.removeListener(onChange);
      vl13.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest14<T1, T2, T3, T4, T5, T6, T7, T8, T9,
    T10, T11, T12, T13, T14, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  ValueListenable<T10> vl10,
  ValueListenable<T11> vl11,
  ValueListenable<T12> vl12,
  ValueListenable<T13> vl13,
  ValueListenable<T14> vl14,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
    T10 v10,
    T11 v11,
    T12 v12,
    T13 v13,
    T14 v14,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
    vl10.value,
    vl11.value,
    vl12.value,
    vl13.value,
    vl14.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
      vl10.value,
      vl11.value,
      vl12.value,
      vl13.value,
      vl14.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);
  vl10.addListener(onChange);
  vl11.addListener(onChange);
  vl12.addListener(onChange);
  vl13.addListener(onChange);
  vl14.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
      vl10.removeListener(onChange);
      vl11.removeListener(onChange);
      vl12.removeListener(onChange);
      vl13.removeListener(onChange);
      vl14.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest15<T1, T2, T3, T4, T5, T6, T7, T8, T9,
    T10, T11, T12, T13, T14, T15, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  ValueListenable<T10> vl10,
  ValueListenable<T11> vl11,
  ValueListenable<T12> vl12,
  ValueListenable<T13> vl13,
  ValueListenable<T14> vl14,
  ValueListenable<T15> vl15,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
    T10 v10,
    T11 v11,
    T12 v12,
    T13 v13,
    T14 v14,
    T15 v15,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
    vl10.value,
    vl11.value,
    vl12.value,
    vl13.value,
    vl14.value,
    vl15.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
      vl10.value,
      vl11.value,
      vl12.value,
      vl13.value,
      vl14.value,
      vl15.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);
  vl10.addListener(onChange);
  vl11.addListener(onChange);
  vl12.addListener(onChange);
  vl13.addListener(onChange);
  vl14.addListener(onChange);
  vl15.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
      vl10.removeListener(onChange);
      vl11.removeListener(onChange);
      vl12.removeListener(onChange);
      vl13.removeListener(onChange);
      vl14.removeListener(onChange);
      vl15.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest16<T1, T2, T3, T4, T5, T6, T7, T8, T9,
    T10, T11, T12, T13, T14, T15, T16, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  ValueListenable<T10> vl10,
  ValueListenable<T11> vl11,
  ValueListenable<T12> vl12,
  ValueListenable<T13> vl13,
  ValueListenable<T14> vl14,
  ValueListenable<T15> vl15,
  ValueListenable<T16> vl16,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
    T10 v10,
    T11 v11,
    T12 v12,
    T13 v13,
    T14 v14,
    T15 v15,
    T16 v16,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
    vl10.value,
    vl11.value,
    vl12.value,
    vl13.value,
    vl14.value,
    vl15.value,
    vl16.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
      vl10.value,
      vl11.value,
      vl12.value,
      vl13.value,
      vl14.value,
      vl15.value,
      vl16.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);
  vl10.addListener(onChange);
  vl11.addListener(onChange);
  vl12.addListener(onChange);
  vl13.addListener(onChange);
  vl14.addListener(onChange);
  vl15.addListener(onChange);
  vl16.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
      vl10.removeListener(onChange);
      vl11.removeListener(onChange);
      vl12.removeListener(onChange);
      vl13.removeListener(onChange);
      vl14.removeListener(onChange);
      vl15.removeListener(onChange);
      vl16.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest17<T1, T2, T3, T4, T5, T6, T7, T8, T9,
    T10, T11, T12, T13, T14, T15, T16, T17, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  ValueListenable<T10> vl10,
  ValueListenable<T11> vl11,
  ValueListenable<T12> vl12,
  ValueListenable<T13> vl13,
  ValueListenable<T14> vl14,
  ValueListenable<T15> vl15,
  ValueListenable<T16> vl16,
  ValueListenable<T17> vl17,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
    T10 v10,
    T11 v11,
    T12 v12,
    T13 v13,
    T14 v14,
    T15 v15,
    T16 v16,
    T17 v17,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
    vl10.value,
    vl11.value,
    vl12.value,
    vl13.value,
    vl14.value,
    vl15.value,
    vl16.value,
    vl17.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
      vl10.value,
      vl11.value,
      vl12.value,
      vl13.value,
      vl14.value,
      vl15.value,
      vl16.value,
      vl17.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);
  vl10.addListener(onChange);
  vl11.addListener(onChange);
  vl12.addListener(onChange);
  vl13.addListener(onChange);
  vl14.addListener(onChange);
  vl15.addListener(onChange);
  vl16.addListener(onChange);
  vl17.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
      vl10.removeListener(onChange);
      vl11.removeListener(onChange);
      vl12.removeListener(onChange);
      vl13.removeListener(onChange);
      vl14.removeListener(onChange);
      vl15.removeListener(onChange);
      vl16.removeListener(onChange);
      vl17.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest18<T1, T2, T3, T4, T5, T6, T7, T8, T9,
    T10, T11, T12, T13, T14, T15, T16, T17, T18, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  ValueListenable<T10> vl10,
  ValueListenable<T11> vl11,
  ValueListenable<T12> vl12,
  ValueListenable<T13> vl13,
  ValueListenable<T14> vl14,
  ValueListenable<T15> vl15,
  ValueListenable<T16> vl16,
  ValueListenable<T17> vl17,
  ValueListenable<T18> vl18,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
    T10 v10,
    T11 v11,
    T12 v12,
    T13 v13,
    T14 v14,
    T15 v15,
    T16 v16,
    T17 v17,
    T18 v18,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
    vl10.value,
    vl11.value,
    vl12.value,
    vl13.value,
    vl14.value,
    vl15.value,
    vl16.value,
    vl17.value,
    vl18.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
      vl10.value,
      vl11.value,
      vl12.value,
      vl13.value,
      vl14.value,
      vl15.value,
      vl16.value,
      vl17.value,
      vl18.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);
  vl10.addListener(onChange);
  vl11.addListener(onChange);
  vl12.addListener(onChange);
  vl13.addListener(onChange);
  vl14.addListener(onChange);
  vl15.addListener(onChange);
  vl16.addListener(onChange);
  vl17.addListener(onChange);
  vl18.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
      vl10.removeListener(onChange);
      vl11.removeListener(onChange);
      vl12.removeListener(onChange);
      vl13.removeListener(onChange);
      vl14.removeListener(onChange);
      vl15.removeListener(onChange);
      vl16.removeListener(onChange);
      vl17.removeListener(onChange);
      vl18.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest19<T1, T2, T3, T4, T5, T6, T7, T8, T9,
    T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  ValueListenable<T10> vl10,
  ValueListenable<T11> vl11,
  ValueListenable<T12> vl12,
  ValueListenable<T13> vl13,
  ValueListenable<T14> vl14,
  ValueListenable<T15> vl15,
  ValueListenable<T16> vl16,
  ValueListenable<T17> vl17,
  ValueListenable<T18> vl18,
  ValueListenable<T19> vl19,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
    T10 v10,
    T11 v11,
    T12 v12,
    T13 v13,
    T14 v14,
    T15 v15,
    T16 v16,
    T17 v17,
    T18 v18,
    T19 v19,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
    vl10.value,
    vl11.value,
    vl12.value,
    vl13.value,
    vl14.value,
    vl15.value,
    vl16.value,
    vl17.value,
    vl18.value,
    vl19.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
      vl10.value,
      vl11.value,
      vl12.value,
      vl13.value,
      vl14.value,
      vl15.value,
      vl16.value,
      vl17.value,
      vl18.value,
      vl19.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);
  vl10.addListener(onChange);
  vl11.addListener(onChange);
  vl12.addListener(onChange);
  vl13.addListener(onChange);
  vl14.addListener(onChange);
  vl15.addListener(onChange);
  vl16.addListener(onChange);
  vl17.addListener(onChange);
  vl18.addListener(onChange);
  vl19.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
      vl10.removeListener(onChange);
      vl11.removeListener(onChange);
      vl12.removeListener(onChange);
      vl13.removeListener(onChange);
      vl14.removeListener(onChange);
      vl15.removeListener(onChange);
      vl16.removeListener(onChange);
      vl17.removeListener(onChange);
      vl18.removeListener(onChange);
      vl19.removeListener(onChange);
    },
  );
}

@useResult
DisposableValueListenable<U> combineLatest20<T1, T2, T3, T4, T5, T6, T7, T8, T9,
    T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, U>(
  ValueListenable<T1> vl1,
  ValueListenable<T2> vl2,
  ValueListenable<T3> vl3,
  ValueListenable<T4> vl4,
  ValueListenable<T5> vl5,
  ValueListenable<T6> vl6,
  ValueListenable<T7> vl7,
  ValueListenable<T8> vl8,
  ValueListenable<T9> vl9,
  ValueListenable<T10> vl10,
  ValueListenable<T11> vl11,
  ValueListenable<T12> vl12,
  ValueListenable<T13> vl13,
  ValueListenable<T14> vl14,
  ValueListenable<T15> vl15,
  ValueListenable<T16> vl16,
  ValueListenable<T17> vl17,
  ValueListenable<T18> vl18,
  ValueListenable<T19> vl19,
  ValueListenable<T20> vl20,
  U Function(
    T1 v1,
    T2 v2,
    T3 v3,
    T4 v4,
    T5 v5,
    T6 v6,
    T7 v7,
    T8 v8,
    T9 v9,
    T10 v10,
    T11 v11,
    T12 v12,
    T13 v13,
    T14 v14,
    T15 v15,
    T16 v16,
    T17 v17,
    T18 v18,
    T19 v19,
    T20 v20,
  ) combine,
) {
  final combinedNotifier = ValueNotifier<U>(combine(
    vl1.value,
    vl2.value,
    vl3.value,
    vl4.value,
    vl5.value,
    vl6.value,
    vl7.value,
    vl8.value,
    vl9.value,
    vl10.value,
    vl11.value,
    vl12.value,
    vl13.value,
    vl14.value,
    vl15.value,
    vl16.value,
    vl17.value,
    vl18.value,
    vl19.value,
    vl20.value,
  ));

  void onChange() {
    combinedNotifier.value = combine(
      vl1.value,
      vl2.value,
      vl3.value,
      vl4.value,
      vl5.value,
      vl6.value,
      vl7.value,
      vl8.value,
      vl9.value,
      vl10.value,
      vl11.value,
      vl12.value,
      vl13.value,
      vl14.value,
      vl15.value,
      vl16.value,
      vl17.value,
      vl18.value,
      vl19.value,
      vl20.value,
    );
  }

  vl1.addListener(onChange);
  vl2.addListener(onChange);
  vl3.addListener(onChange);
  vl4.addListener(onChange);
  vl5.addListener(onChange);
  vl6.addListener(onChange);
  vl7.addListener(onChange);
  vl8.addListener(onChange);
  vl9.addListener(onChange);
  vl10.addListener(onChange);
  vl11.addListener(onChange);
  vl12.addListener(onChange);
  vl13.addListener(onChange);
  vl14.addListener(onChange);
  vl15.addListener(onChange);
  vl16.addListener(onChange);
  vl17.addListener(onChange);
  vl18.addListener(onChange);
  vl19.addListener(onChange);
  vl20.addListener(onChange);

  return ValueListenableView(
    combinedNotifier,
    dispose: () {
      combinedNotifier.dispose();
      vl1.removeListener(onChange);
      vl2.removeListener(onChange);
      vl3.removeListener(onChange);
      vl4.removeListener(onChange);
      vl5.removeListener(onChange);
      vl6.removeListener(onChange);
      vl7.removeListener(onChange);
      vl8.removeListener(onChange);
      vl9.removeListener(onChange);
      vl10.removeListener(onChange);
      vl11.removeListener(onChange);
      vl12.removeListener(onChange);
      vl13.removeListener(onChange);
      vl14.removeListener(onChange);
      vl15.removeListener(onChange);
      vl16.removeListener(onChange);
      vl17.removeListener(onChange);
      vl18.removeListener(onChange);
      vl19.removeListener(onChange);
      vl20.removeListener(onChange);
    },
  );
}
